### ISSUE TITLE
Undefined methods

### ISSUE THREAD

**Issue by SchellerCyberSecurity** [rapid7/nexpose-resources#3]
While trying to use the analyze_load_ignore_discover.rb script I am being told that engine_id is an undefined method. There were others but I believe I got them fixed so as of right now I am trying to find out what is going on.

**Comment by gschneider-r7** [comment]
Can you paste the output from the error? I am guessing the object its referring to is `nil`, probably from a site that has no scan history.

If so you can add this after line 17:

```ruby
next if last_scan.nil?
```

Aside from that these are some old scripts and haven't been updated to use the latest versions of the gem, though this one doesn't seem to use anything that has changed over the years.

**Comment by SchellerCyberSecurity** [comment]
anazlyze_load_ignore_discovery.rb:37:in 'block in <main>': undefined method 'engine_id' for nil:NilClass (NoMethodError)
     from analyze_load_ignore_discovery.rb:31:in 'each'
     from analyze_load_ignore_discovery.rb:31:in 'method'

Mind you the line numbers are off as I added in the capability to input username/password/console

**Comment by SchellerCyberSecurity** [comment]
ok it took out portions due to tags.

**Comment by gschneider-r7** [comment]
Sorry it's not clear from your last reply - is there another issue occurring or did my suggestion work for you? If you're still having issues with the script it would help to see your modified version. You can post it to https://gist.github.com/ and link to the gist in a reply here. Be aware of any private details in your script that you don't want to share with the world, of course. 😉

**Comment by SchellerCyberSecurity** [comment]
Gavin,

See below for the link.

https://gist.github.com/SchellerCyberSecurity/b758480ef34332481b8ae9cc19c45e78

I prefer python, ruby is a completely different animal it seems lol.



Derek M Scheller Jr
CCNA R/S, CCNA-Security, CEH, CPT, GSEC, GCED, GCIH, GPYC
Cell: 443-805-0239
https://schellercybersecurity.blogspot.com

**Comment by gschneider-r7** [comment]
Okay you can see my edit here where I added a line to skip when a site had no scans: https://gist.github.com/gschneider-r7/1e1e547be80936fb14a36f92abbfbba9#file-analyze_load_ignore_discovery_login_creds-rb-L37

Aside from adding that line I un-indented a few lines, which doesn't change anything functionally (this isn't Python after all 😉 )

If you still see errors, when you post them you can wrap the output in a code block like this:

\```
errors here
\```

which will convert to:

```
errors here
```

**Comment by SchellerCyberSecurity** [comment]
Gavin,

I had put that line in before and still got the same error that I sent you.


Derek M Scheller Jr
CCNA R/S, CCNA-Security, CEH, CPT, GSEC, GCED, GCIH, GPYC
Cell: 443-805-0239
https://schellercybersecurity.blogspot.com

**Comment by SchellerCyberSecurity** [comment]
analyze_load_ignore_discovery.rb:46:in `block in <main>': undefined method
`name' for nil:NilClass (NoMethodError)
    from analyze_load_ignore_discovery.rb:45:in `each'
    from analyze_load_ignore_discovery.rb:45:in `<main>'


Derek M Scheller Jr
CCNA R/S, CCNA-Security, CEH, CPT, GSEC, GCED, GCIH, GPYC
Cell: 443-805-0239
https://schellercybersecurity.blogspot.com

**Comment by gschneider-r7** [comment]
Updated the gist with a check on the engine, seems you have one that can't be found by ID for some reason. https://gist.github.com/gschneider-r7/1e1e547be80936fb14a36f92abbfbba9#file-analyze_load_ignore_discovery_login_creds-rb-L47-L51
